-- 20260527_clonamivoz_preview_and_payment.sql
--
-- Adds preview + Stripe payment columns to cloned_voice_songs and expands
-- the status enum to cover the new lifecycle:
--
--   pending → generating_lyrics → lyrics_ready → generating_preview →
--   preview_ready → awaiting_payment → paid → generating_song →
--   success | failed
--
-- Why this flow
-- -------------
-- Customer records voice → picks genre → fills story (free).
-- Lyrics generated by Claude (~$0.001, free to customer).
-- We then generate a SHORT preview using their voice + a hardcoded
-- 4-line preview hook (~$0.10 of Suno quota).
-- Customer hears themselves singing.
-- Customer pays $69 via Stripe.
-- Webhook fires generate-cloned-voice-song with their actual lyrics →
-- 2 full variants delivered.
--
-- This migration is additive. Existing rows keep their current status
-- (pending/generating_lyrics/generating_song/success/failed). The new
-- states are only reachable via the new flow.

-- ---------------------------------------------------------------------------
-- 1. New columns on cloned_voice_songs
-- ---------------------------------------------------------------------------

ALTER TABLE public.cloned_voice_songs
  ADD COLUMN IF NOT EXISTS preview_audio_url    TEXT,
  ADD COLUMN IF NOT EXISTS preview_kie_task_id  TEXT,
  ADD COLUMN IF NOT EXISTS preview_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS stripe_session_id    TEXT,
  ADD COLUMN IF NOT EXISTS stripe_payment_intent TEXT,
  ADD COLUMN IF NOT EXISTS paid                 BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS paid_at              TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS amount_cents         INTEGER;

COMMENT ON COLUMN public.cloned_voice_songs.preview_audio_url      IS 'Permanent URL of the 15-30s preview generated BEFORE payment (so the customer hears themselves before paying).';
COMMENT ON COLUMN public.cloned_voice_songs.preview_kie_task_id    IS 'Kie task id for the preview generation. Different from kie_task_id which is for the full song.';
COMMENT ON COLUMN public.cloned_voice_songs.preview_completed_at   IS 'When the preview generation finished.';
COMMENT ON COLUMN public.cloned_voice_songs.stripe_session_id      IS 'Stripe checkout.session id. Used to look up the order from the webhook.';
COMMENT ON COLUMN public.cloned_voice_songs.stripe_payment_intent  IS 'Stripe payment_intent id once the session completes. For refund traceability.';
COMMENT ON COLUMN public.cloned_voice_songs.paid                   IS 'True after the Stripe webhook confirms payment. Gates the full song generation.';
COMMENT ON COLUMN public.cloned_voice_songs.paid_at                IS 'When the Stripe webhook marked this paid.';
COMMENT ON COLUMN public.cloned_voice_songs.amount_cents           IS 'Amount paid in USD cents (6900 for the launch tier).';


-- ---------------------------------------------------------------------------
-- 2. Expanded status CHECK constraint
-- ---------------------------------------------------------------------------
-- Drop + recreate. The OLD states (pending, generating_lyrics, generating_song,
-- success, failed) all stay valid. We're ADDING the new ones.

ALTER TABLE public.cloned_voice_songs
  DROP CONSTRAINT IF EXISTS cloned_voice_songs_status_check;

ALTER TABLE public.cloned_voice_songs
  ADD CONSTRAINT cloned_voice_songs_status_check
  CHECK (status IN (
    'pending',
    'generating_lyrics',
    'lyrics_ready',          -- NEW: Claude lyrics ready, awaiting preview generation
    'generating_preview',    -- NEW: Suno preview job in flight
    'preview_ready',         -- NEW: preview done, awaiting customer payment decision
    'awaiting_payment',      -- NEW: customer clicked "pay" → in Stripe checkout
    'paid',                  -- NEW: Stripe webhook confirmed; full song queued
    'generating_song',
    'success',
    'failed'
  ));


-- ---------------------------------------------------------------------------
-- 3. Indexes for the new lookup paths
-- ---------------------------------------------------------------------------

-- The Stripe webhook arrives with a session_id; we look up the row by it.
CREATE INDEX IF NOT EXISTS cloned_voice_songs_stripe_session_idx
  ON public.cloned_voice_songs (stripe_session_id)
  WHERE stripe_session_id IS NOT NULL;

-- The preview function uses preview_kie_task_id during polling.
CREATE INDEX IF NOT EXISTS cloned_voice_songs_preview_task_idx
  ON public.cloned_voice_songs (preview_kie_task_id)
  WHERE preview_kie_task_id IS NOT NULL;

-- Ops: "show me all paid songs", "show me unpaid abandoned previews".
CREATE INDEX IF NOT EXISTS cloned_voice_songs_paid_idx
  ON public.cloned_voice_songs (paid, created_at DESC);
